---
title: "Delhi Regression Tuning"
author: "Michael Murray"
date: "November 18, 2015"
output: html_document
---

```{r, echo = FALSE}
setwd("~/Spatial Segmentation/India")
delhi <- read.csv("delhi.csv")
library(geosphere)
```

```{r}
delhi$airport.lat <- 28.6017668
delhi$airport.lon <- 77.212669

p1 <- matrix(c(delhi$Longitude,delhi$Latitude),nrow=length(delhi$Longitude),ncol=2)
p2 <- matrix(c(delhi$airport.lon,delhi$airport.lat),nrow=length(delhi$Longitude),ncol=2)

India.Gate <- distHaversine(p1,p2)

delhi <- data.frame(delhi, India.Gate)
```

```{r}
delhi.lm.poi <- lm(hp ~ rooms + property + Connaught.Place + Laxmi.Nagar +airport + bar + cemetery + golf + industrial + parking + petrol + tourist + amusement + bus.dist.half +community + highered + library + parkinglot + train.dist.half + police + business + commuterrail.dist.half + hospital + school + park.dist.km+ large.building + Indira.Ghandi + India.Gate, data = delhi)

summary(delhi.lm.poi)
```

```{r}
delhi.lm.poi2 <- lm(hp ~ rooms + property + Connaught.Place + Laxmi.Nagar +airport + bar + cemetery + golf + industrial + parking + petrol + tourist + amusement + bus.dist.half +community + highered + library + parkinglot + train.dist.half + police + business + commuterrail.dist.half + hospital + school + park.dist.km+ large.building + Indira.Ghandi, data = delhi)

summary(delhi.lm.poi2)
```
